JFEED2023-63 création de la méthode extraireInfoDistributeur() pour extraire les informations d'un distributeur dans un JSON
btssn-lasalle-84/just-feed-2023 pull request #49
Opened 2023-06-02 13:32 UTC by Async-Mayeul

Bonjour,
Pour stocker les données mesurées, est-il possible que je crée une table `Mesures` dans la base de données ?

2023-06-02 13:55 UTC, tvaira commented
> Bonjour, Pour stocker les données mesurées, est-il possible que je crée une table `Mesures` dans la base de données ?

Tu veux stocker quoi ? Peux-tu proposer un code SQL pour cette table ?

2023-06-05 18:25 UTC, tvaira requested changes
Il faut retrouver l'affichage comme il était avant : avec l'ensemble des distributeurs. Les message MQTT doivent juste mettre à jour les données affichées.

2023-06-05 18:25 UTC, tvaira commented on JustFeedAndroid/app/src/main/java/com/justfeed/justfeedandroid/BaseDeDonnees.java
> -    public void recupererDistributeurs()
Il faut cette méthode pour récupérer l'ensemble des distributeurs et les afficher comme avant !

2023-06-05 18:25 UTC, tvaira commented on JustFeedAndroid/app/src/main/java/com/justfeed/justfeedandroid/JustFeed.java
>      private static final String TOPIC_SIM1 = "distributeur-1-sim"; //!< Topic MQTT du simulateur 1
A supprimer !

2023-06-05 18:25 UTC, tvaira commented on JustFeedAndroid/app/src/main/java/com/justfeed/justfeedandroid/JustFeed.java
> +    private static final String TOPIC_SIM2 = "distributeur-2-sim"; //!< Topic MQTT du simulateur 2
A supprimer !

2023-06-05 18:25 UTC, tvaira commented on JustFeedAndroid/app/src/main/java/com/justfeed/justfeedandroid/JustFeed.java
> +    private static final String TOPICS = "#"; //!< S'abonne à tout les topics
Non ! Juste vide `""`

2023-06-06 08:40 UTC, Async-Mayeul commented
> > Bonjour, Pour stocker les données mesurées, est-il possible que je crée une table `Mesures` dans la base de données ?
> 
> Tu veux stocker quoi ? Peux-tu proposer un code SQL pour cette table ?

Non j'ai réfléchi et cela ne me semble pas être une bonne idée.

2023-06-06 16:21 UTC, tvaira requested changes
J'aimerais un affichage simplement comme ceci : **Gare Orange (distributeur-1-sim)**

Le Log sur les requêtes UPADTE montre qu'il manque un esapce avant le WHERE (même si la requête fonctionne) : `executerRequete() requete = UPDATE Bac SET Bac.remplissage = 32.0WHERE Bac.idDistributeur ...`

Ne manquerait-il pas un : `adapteurDistributeur.notifyDataSetChanged();` ? car les données ne sont pas rafraîchies dans la vue.

2023-06-07 20:08 UTC, tvaira submitted a review, later dismissed

2023-06-07 20:09 UTC, tvaira commented
Voir : saisir la virgule `,` ? éviter la modification à chaque changement de l'édition du prix ?

2023-06-08 20:32 UTC, tvaira approved these changes

2023-06-09 07:05 UTC, merged